# Tensors

## Introduction to Tensors

At the core of PyTorch lies the `Tensor` object, which serves as the fundamental data structure for all computations. Tensors are multidimensional arrays, conceptually similar to NumPy arrays, but with added capabilities tailored for deep learning and high-performance computing.

PyTorch tensors support a wide variety of operations, including arithmetic, indexing, reshaping, and broadcasting. More importantly, they can be transferred seamlessly between the CPU and GPU, allowing for accelerated computation with minimal code changes.

In practice, tensors represent everything from scalar values to high-dimensional data such as images, sequences, and model parameters. Understanding tensors and how to manipulate them efficiently is essential for working with PyTorch and developing neural network models.

PyTorch tensors are created using [`torch.tensor`](https://pytorch.org/docs/stable/tensors.html). For example, we may create the simplest tensor – a scalar – in the following way:


In [1]:
import torch
# scalar
scalar = torch.tensor(2)
scalar

tensor(2)

A scalar is a $0$-dimensional tensor. As a matter of fact, we can check its dimension with `ndim`

In [2]:
scalar.ndim


0

To access the value of a tensor, we must use the `item()` method: 

In [3]:
scalar.item()

2

The next structure is just a vector, i.e. a tensor of dimension $2$. We can create it using the torch.tensor() constructor from a simple python list:

In [4]:
# vector
vector = torch.tensor([2, 7])
vector

tensor([2, 7])

Note: be careful using `tensor()` instead of `Tensor()`. The latter is a lower-level class constructor. When given shape arguments (e.g., `torch.Tensor(2, 3)`), it creates an *uninitialized* tensor. This can lead to unintended behavior. So, always use `torch.tensor()` when starting from data.


Now, tensors' dimensions and their shapes are very important in PyTorch. When manipulating vectors, we must pay close attention to their shapes, or we may run into errors or miscalculations.


In [5]:
vector.ndim


1

This is different from vector.shape:

In [6]:
vector.shape


torch.Size([2])

We can step things up and create a matrix:

In [7]:
matrix = torch.tensor([[1, 2], [7, 8]])
matrix

tensor([[1, 2],
        [7, 8]])

In [8]:
print(f"matrix dims: {matrix.ndim}")
print(f"matrix shape: {matrix.shape}")


matrix dims: 2
matrix shape: torch.Size([2, 2])


This tells us that our matrix is 2-dimensional, and in fact it's a 2×2 square matrix. How about a rectangular matrix? Very simple:
<!--  -->

In [9]:
rect_matrix = torch.tensor([[1, 2], [3, 4], [4, 5]])
print(f"matrix dims: {rect_matrix.ndim}")
print(f"matrix shape: {rect_matrix.shape}")


matrix dims: 2
matrix shape: torch.Size([3, 2])


Since we have $2$ elements along each axes, and it's a $3\times2$ matrix.  
Let's see how it works with tensors:

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5],
                        [6, 7, 8]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [6, 7, 8]]])

In [11]:
print(f"Tensor dim: {TENSOR.ndim}")


Tensor dim: 3


In [12]:
print(f"Tensor shape: {TENSOR.shape}")


Tensor shape: torch.Size([1, 4, 3])


Why this shape? We can think of tensors as multidimensional matrices. In this case, we have 1 matrix containing 4 vectors of dimension 3.

Understanding shapes takes some practice, but once you get used to it, it becomes second nature.

Let's clarify with one last example: let's say we want to feed our network RGB images. We usually encode the image data as tensors:


In [13]:
x = torch.tensor([
    [  # First image
        [[1, 2, 3], [4, 5, 6], [7, 8, 9]],     # Red channel
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  # Green channel
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]   # Blue channel
    ],
    [  # Second image
        [[28, 29, 30], [31, 32, 33], [34, 35, 36]],
        [[37, 38, 39], [40, 41, 42], [43, 44, 45]],
        [[46, 47, 48], [49, 50, 51], [52, 53, 54]]
    ]
])


This represents 2 images, each of size 3×3 pixels, with 3 channels (RGB).


## Random Tensors