# Tensors

## Introduction to Tensors

At the core of PyTorch lies the `Tensor` object, which serves as the fundamental data structure for all computations. Tensors are multidimensional arrays, conceptually similar to NumPy arrays, but with added capabilities tailored for deep learning and high-performance computing.

PyTorch tensors support a wide variety of operations, including arithmetic, indexing, reshaping, and broadcasting. More importantly, they can be transferred seamlessly between the CPU and GPU, allowing for accelerated computation with minimal code changes.

In practice, tensors represent everything from scalar values to high-dimensional data such as images, sequences, and model parameters. Understanding tensors and how to manipulate them efficiently is essential for working with PyTorch and developing neural network models.

PyTorch tensors are created using [`torch.tensor`](https://pytorch.org/docs/stable/tensors.html). For example, we may create the simplest tensor – a scalar – in the following way:


In [69]:
import torch
# scalar
scalar = torch.tensor(2)
scalar

tensor(2)

A scalar is a $0$-dimensional tensor. As a matter of fact, we can check its dimension with `ndim`

In [70]:
scalar.ndim


0

To access the value of a tensor, we must use the `item()` method: 

In [71]:
scalar.item()

2

The next structure is just a vector, i.e. a tensor of dimension $2$. We can create it using the torch.tensor() constructor from a simple python list:

In [72]:
# vector
vector = torch.tensor([2, 7])
vector

tensor([2, 7])

Note: be careful using `tensor()` instead of `Tensor()`. The latter is a lower-level class constructor. When given shape arguments (e.g., `torch.Tensor(2, 3)`), it creates an *uninitialized* tensor. This can lead to unintended behavior. So, always use `torch.tensor()` when starting from data.


Now, tensors' dimensions and their shapes are very important in PyTorch. When manipulating vectors, we must pay close attention to their shapes, or we may run into errors or miscalculations.


In [73]:
vector.ndim


1

This is different from vector.shape:

In [74]:
vector.shape


torch.Size([2])

We can step things up and create a matrix:

In [75]:
matrix = torch.tensor([[1, 2], [7, 8]])
matrix

tensor([[1, 2],
        [7, 8]])

In [76]:
print(f"matrix dims: {matrix.ndim}")
print(f"matrix shape: {matrix.shape}")


matrix dims: 2
matrix shape: torch.Size([2, 2])


This tells us that our matrix is 2-dimensional, and in fact it's a 2×2 square matrix. How about a rectangular matrix? Very simple:
<!--  -->

In [77]:
rect_matrix = torch.tensor([[1, 2], [3, 4], [4, 5]])
print(f"matrix dims: {rect_matrix.ndim}")
print(f"matrix shape: {rect_matrix.shape}")


matrix dims: 2
matrix shape: torch.Size([3, 2])


Since we have $2$ elements along each axes, and it's a $3\times2$ matrix.  
Let's see how it works with tensors:

In [78]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5],
                        [6, 7, 8]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [6, 7, 8]]])

In [79]:
print(f"Tensor dim: {TENSOR.ndim}")


Tensor dim: 3


In [80]:
print(f"Tensor shape: {TENSOR.shape}")


Tensor shape: torch.Size([1, 4, 3])


Why this shape? We can think of tensors as multidimensional matrices. In this case, we have 1 matrix containing 4 vectors of dimension 3.

Understanding shapes takes some practice, but once you get used to it, it becomes second nature.

This represents 2 images, each of size 3×3 pixels, with 3 channels (RGB).


## Random Tensors

Random tensors are very important in PyTorch's workflows. The reason is the way Neural Networks work. They start from randomly initialized weights, and they adapt these values through training (by minimizing a Loss function). So the first step is always to intialize weights randomly. 

In order to create random tensors we can use Torch's [torch.rand()](https://docs.pytorch.org/docs/main/generated/torch.rand.html). 

In [81]:
random_tensor = torch.rand(3,4)
random_tensor
print(f"random tensor dimension: {random_tensor.ndim}") # dims will be 2
print(f"random tensor shape: {random_tensor.shape}") # shape will be torch.Size([3,4])

random tensor dimension: 2
random tensor shape: torch.Size([3, 4])


A common example of tensor encoding is when we want to encode an image. Usually to encode an image we use a tensor of shapes `[colour_channels, height, width]`. For an RGB image of size `224 x 224`we will use something like this:

![Example of encoding an RGB image](imgs/00-tensor-shape-example-of-image.png)

## 0's and 1's Tensors
These are useful for creating masks.


In [82]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [83]:
# create a tensor of all zeros
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Note: when you let Torch automatically create a tensor, its default type is `torch.float32`. To get the type we can use the `.dtype` argument. We will see more about types in the future.

In [84]:
ones.dtype

torch.float32

## Creating range of tensors & tensors-like

In [85]:
# use torch.range()
one_to_Ten = torch.arange(1,11)
one_to_Ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Basically its parameters are start, end (ends at end-1) and steps. by default the step is $1$ but we can modify it:

In [86]:
zero_to_hundred = torch.arange(start=0, end=100, step=2)
zero_to_hundred

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Another useful method is the `_like()` method. For example, `zeros_like()`  allows us to create a tensor with the shape of another already existing tensor, all filled with zeros. There are many options, you can fill it with chosen values (`torch.full_like()`) , with random numbers (`torch.rand_like()`), and so on.  

In [87]:
ten_zeros = torch.zeros_like(one_to_Ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

The standard type is float32, but we can change it of course by explicitly setting it. See [torch.dtype](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-dtype).

In [88]:
# Float 32 tensor
float_32_tensor = torch.rand(2 ,6)
float_32_tensor

tensor([[0.3513, 0.6349, 0.8420, 0.9925, 0.9101, 0.7914],
        [0.1295, 0.1268, 0.9806, 0.1038, 0.3814, 0.0941]])

In [89]:
float_32_tensor.dtype

torch.float32

In [90]:
# Float 16 tensor
float_16_tensor = torch.rand((2 ,6), dtype=torch.float16)
float_16_tensor.dtype

torch.float16

Or, if you are creating a tensor from scratch, you can specify it in the same way

In [91]:
data = [3, 6, 9, 10]
tensor = torch.tensor(data, dtype=torch.float16)
tensor 

tensor([ 3.,  6.,  9., 10.], dtype=torch.float16)

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).



`.dtype` is one of the three main arguments in the `tensor()` class. The other two are just as important - if not more - and we will see more about them later on. They are the `device` argument, which specify on which device (cpu or gpu) our machine should create our tensor, and `requires_grad`, which specifies if we should keep track of operations performed on our tensor in order to perform backpropagation. 

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What dataype is the tensor, defaults to torch.float32 (even if it's set to None)
                               device='cpu', # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients for backpropagation (default False if not wrapped in nn.Parameter)

float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad

(torch.float32, device(type='cpu'), False)